### PR TITLE
fix(documentation): update docs to reflect current usage

### PR DESCRIPTION
**Pull request by TriStarGod**

### CODE REVIEW

**Comment by TriStarGod** [comment]
I added the `outline` array with 0 values. Not sure what values should be used.

**Comment by Romakita** [comment]
```
    outline: {
      none: ['2px solid transparent', '2px'],
      white: ['2px dotted white', '2px'],
      black: ['2px dotted black', '2px'],
    },
```

**Comment by Romakita** [comment]
Also, there is a convention for the commit (@commitlint/config-conventional should have blocked the commit).

Please rewrite your commit using the angular commit convention:

```
fix(tailwind): your message
```

See you
Romain

**Comment by Romakita** [comment]
Why have you closed this PR ?

**Pull request closed without merging**
